import Config

# Configure your database
config :courier, Courier.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "courier_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :courier, CourierWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "AmMyfvysE7S6XSLMEx5pqbOxk5KgHTcZJK8OtDEPbNwpuqQDoGBdCeCHmvmDTuLj",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :courier, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Transactional email in dev. `COURIER_MAIL_ADAPTER=none` is the way to get the
# Local adapter — it renders into memory, returns a provider-shaped message id,
# and never opens a socket, so dev cannot accidentally mail a real person.
#
# It is NOT set here, and that is the change this packet made. A committed
# `adapter: Swoosh.Adapters.Local` is a silent default: it applies to every
# developer who has not overridden it, it is invisible in a diff, and it is the
# exact configuration that shipped. The adapter now comes from the environment
# (config/runtime.exs, via `Courier.MailerAdapter`), which is unset here — so a
# developer who starts courier without setting it gets a refusal naming the
# variable rather than a mailer that silently works.
#
# To work on courier's templates without a relay:
#
#     COURIER_MAIL_ADAPTER=none mix phx.server
#
# The Swoosh preview plug is deliberately not wired — courier has no HTML layer to
# preview into.
