defmodule Courier.SecretBoxTest do
  @moduledoc """
  A webhook signing secret is a credential: anyone holding it can forge a
  delivery that courier's brand is on. The one thing that must be true of it at
  rest is that it is not readable from the database.

  "Not plaintext" is asserted against the *column*, not against a helper: a test
  that called `SecretBox.seal/1` and then asked `SecretBox.open/1` would pass
  even if `seal/1` returned the input, because both ends would agree. These read
  the row.
  """

  use Courier.DataCase, async: true

  alias Courier.SecretBox
  alias Courier.WebhookEndpoint
  alias Courier.WebhookEndpoints

  @account_id "6f5d4c3b-2a19-4e8f-9c07-1b2d3e4f5061"

  defp endpoint! do
    {:ok, endpoint, _secret} =
      WebhookEndpoints.create(%{url: "https://hooks.example.com/events", account_id: @account_id})

    endpoint
  end

  # The column read as raw SQL, not through the schema — the point of the "at
  # rest" block is what is on disk, and a test that went through Ecto would be
  # reading whatever the schema claims the column is rather than what it holds.
  defp stored_column(endpoint) do
    %{rows: [[stored]]} =
      Repo.query!("SELECT secret FROM webhook_endpoints WHERE id = $1::uuid", [
        Ecto.UUID.dump!(endpoint.id)
      ])

    stored
  end

  describe "at rest" do
    test "the column is not the secret" do
      endpoint = endpoint!()
      secret = WebhookEndpoints.plaintext_secret(endpoint)

      assert String.starts_with?(secret, "whsec_")
      refute stored_column(endpoint) == secret
    end

    test "the column does not contain the secret's base64, even as a substring" do
      endpoint = endpoint!()
      encoded = WebhookEndpoints.plaintext_secret(endpoint) |> String.replace_prefix("whsec_", "")

      refute stored_column(endpoint) =~ encoded
    end

    test "the column is not recognisable as a whsec_ secret" do
      endpoint = endpoint!()

      refute stored_column(endpoint) =~ "whsec_"
    end

    test "two endpoints with different secrets have different stored bytes" do
      one = endpoint!()

      {:ok, other, _secret} =
        WebhookEndpoints.create(%{
          url: "https://other.example.com/events",
          account_id: @account_id
        })

      refute stored_column(one) == stored_column(other)
    end

    test "the same secret sealed twice is not the same bytes, so the column is not a password hash in disguise" do
      secret = SecretBox.generate()

      refute SecretBox.seal(secret) == SecretBox.seal(secret)
    end
  end

  describe "round trip" do
    test "sealing and opening gives the secret back" do
      secret = SecretBox.generate()

      assert {:ok, ^secret} = secret |> SecretBox.seal() |> SecretBox.open()
    end

    test "a secret with dots, dashes and mixed case survives" do
      secret = "whsec_" <> Base.encode64("a.b-C_d!" <> :crypto.strong_rand_bytes(8))

      assert {:ok, ^secret} = secret |> SecretBox.seal() |> SecretBox.open()
    end

    test "opening the wrong ciphertext fails rather than returning garbage" do
      sealed = SecretBox.seal(SecretBox.generate())

      assert {:error, :invalid_ciphertext} = SecretBox.open(sealed <> "x")
    end

    test "a ciphertext sealed with another key does not open" do
      sealed = SecretBox.seal(SecretBox.generate(), other_key())

      assert {:error, :invalid_ciphertext} = SecretBox.open(sealed)
    end

    test "a value that was never sealed is refused, not decoded into noise" do
      assert {:error, :invalid_ciphertext} = SecretBox.open("whsec_not_sealed_at_all")
    end
  end

  describe "through the schema" do
    test "the secret a caller receives is the one the row opens to" do
      endpoint = endpoint!()
      secret = WebhookEndpoints.plaintext_secret(endpoint)

      # Not "the column equals the secret" — the column is the ciphertext, and
      # asserting equality there is asserting the bug. What has to hold is that
      # the value the customer was given is the value courier signs with later.
      reloaded = Repo.get!(WebhookEndpoint, endpoint.id)

      assert {:ok, ^secret} = WebhookEndpoints.secret(reloaded)
    end

    test "the column a fresh read sees is still ciphertext, not what the caller was handed" do
      endpoint = endpoint!()
      secret = WebhookEndpoints.plaintext_secret(endpoint)

      refute Repo.get!(WebhookEndpoint, endpoint.id).secret == secret
    end

    test "the secret is generated by courier, never taken from the request" do
      # A body that names its own secret must not be able to set one, for the
      # same reason `user_id` is not cast in `NotificationPreference`: a field the
      # caller controls that names a credential is a field the caller owns.
      assert {:ok, endpoint, secret} =
               WebhookEndpoints.create(%{
                 url: "https://hooks.example.com/events",
                 account_id: @account_id,
                 secret: "whsec_attacker_supplied"
               })

      refute secret == "whsec_attacker_supplied"
      refute stored_column(endpoint) =~ "attacker"
    end
  end

  defp other_key, do: :crypto.strong_rand_bytes(32)
end
