defmodule CourierWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :courier

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_courier_key",
    signing_salt: "RHFMuout",
    same_site: "Lax"
  ]

  # socket "/live", Phoenix.LiveView.Socket,
  #   websocket: [connect_info: [session: @session_options]],
  #   longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :courier,
    gzip: not code_reloading?,
    only: CourierWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Trace first, before anything that can raise: Plug.Static raises in dev,
  # Plug.Parsers raises on a body it cannot read, and the router raises
  # NoRouteError on a path courier does not serve. All three are rendered by
  # CourierWeb.ErrorJSON out of the assigns this plug leaves behind, and all
  # three are answered from the same trace id.
  plug CourierWeb.Plugs.Trace

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :courier
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # Plug.Parsers, with courier's answer for a body it cannot parse — see
  # CourierWeb.Plugs.ParseBody for why that is a module of its own.
  plug CourierWeb.Plugs.ParseBody,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug CourierWeb.Plugs.ProblemContentType
  plug CourierWeb.Router
end
